#!/usr/bin/env bash

#https://whoisds.com//whois-database/newly-registered-domains/2018-10-01.zip/nrd
DB="new_domains.db"
DN="domain-names"

today="$(date -v -1d +"%Y-%m-%d")"
curl "https://whoisds.com//whois-database/newly-registered-domains/$today.zip/nrd" -o $today.zip
unzip -l $today.zip
unzip $today.zip
echo "*** CLEANING FILE"
echo "*** CONVERTING TO CSV"
cat $DN.txt|awk '{ print "0,", $1}' > $DN.csv

# IF DB DOESNT EXIST, MAKE IT
if [ ! -e $DB ]; then
    echo "*** DATABASE NOT FOUND. CREATING"
    printf 'create table domains(id number, domain varchar(200));\n.mode csv\n.import domain-names.csv domains\n' | sqlite3 $DB
else
    # IF SQLITE DB EXISTS USE THAT
    echo "*** DATABASE FOUND."
    sqlite3 $DB ".import domain-names.csv domains"
    du -hs $DB
fi
# clean up
echo "*** CLEANING UP"
read -p "Clean Files ?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm -v $today.zip
    rm -v $DN.txt
    rm -v $DN.csv
fi
